# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import session_manager_pb2 as session__manager__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in session_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SessionManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnSessionCreated = channel.unary_unary(
                '/accelbyte.session.manager.SessionManager/OnSessionCreated',
                request_serializer=session__manager__pb2.SessionCreatedRequest.SerializeToString,
                response_deserializer=session__manager__pb2.SessionResponse.FromString,
                _registered_method=True)
        self.OnSessionUpdated = channel.unary_unary(
                '/accelbyte.session.manager.SessionManager/OnSessionUpdated',
                request_serializer=session__manager__pb2.SessionUpdatedRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.OnSessionDeleted = channel.unary_unary(
                '/accelbyte.session.manager.SessionManager/OnSessionDeleted',
                request_serializer=session__manager__pb2.SessionDeletedRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.OnPartyCreated = channel.unary_unary(
                '/accelbyte.session.manager.SessionManager/OnPartyCreated',
                request_serializer=session__manager__pb2.PartyCreatedRequest.SerializeToString,
                response_deserializer=session__manager__pb2.PartyResponse.FromString,
                _registered_method=True)
        self.OnPartyUpdated = channel.unary_unary(
                '/accelbyte.session.manager.SessionManager/OnPartyUpdated',
                request_serializer=session__manager__pb2.PartyUpdatedRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.OnPartyDeleted = channel.unary_unary(
                '/accelbyte.session.manager.SessionManager/OnPartyDeleted',
                request_serializer=session__manager__pb2.PartyDeletedRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class SessionManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OnSessionCreated(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnSessionUpdated(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnSessionDeleted(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnPartyCreated(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnPartyUpdated(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnPartyDeleted(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnSessionCreated': grpc.unary_unary_rpc_method_handler(
                    servicer.OnSessionCreated,
                    request_deserializer=session__manager__pb2.SessionCreatedRequest.FromString,
                    response_serializer=session__manager__pb2.SessionResponse.SerializeToString,
            ),
            'OnSessionUpdated': grpc.unary_unary_rpc_method_handler(
                    servicer.OnSessionUpdated,
                    request_deserializer=session__manager__pb2.SessionUpdatedRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'OnSessionDeleted': grpc.unary_unary_rpc_method_handler(
                    servicer.OnSessionDeleted,
                    request_deserializer=session__manager__pb2.SessionDeletedRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'OnPartyCreated': grpc.unary_unary_rpc_method_handler(
                    servicer.OnPartyCreated,
                    request_deserializer=session__manager__pb2.PartyCreatedRequest.FromString,
                    response_serializer=session__manager__pb2.PartyResponse.SerializeToString,
            ),
            'OnPartyUpdated': grpc.unary_unary_rpc_method_handler(
                    servicer.OnPartyUpdated,
                    request_deserializer=session__manager__pb2.PartyUpdatedRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'OnPartyDeleted': grpc.unary_unary_rpc_method_handler(
                    servicer.OnPartyDeleted,
                    request_deserializer=session__manager__pb2.PartyDeletedRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'accelbyte.session.manager.SessionManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('accelbyte.session.manager.SessionManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SessionManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OnSessionCreated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accelbyte.session.manager.SessionManager/OnSessionCreated',
            session__manager__pb2.SessionCreatedRequest.SerializeToString,
            session__manager__pb2.SessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnSessionUpdated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accelbyte.session.manager.SessionManager/OnSessionUpdated',
            session__manager__pb2.SessionUpdatedRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnSessionDeleted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accelbyte.session.manager.SessionManager/OnSessionDeleted',
            session__manager__pb2.SessionDeletedRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnPartyCreated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accelbyte.session.manager.SessionManager/OnPartyCreated',
            session__manager__pb2.PartyCreatedRequest.SerializeToString,
            session__manager__pb2.PartyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnPartyUpdated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accelbyte.session.manager.SessionManager/OnPartyUpdated',
            session__manager__pb2.PartyUpdatedRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnPartyDeleted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accelbyte.session.manager.SessionManager/OnPartyDeleted',
            session__manager__pb2.PartyDeletedRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
