# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.proto import session_manager_pb2 as app_dot_proto_dot_session__manager__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class SessionManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnSessionCreated = channel.unary_unary(
                '/accelbyte.session.manager.SessionManager/OnSessionCreated',
                request_serializer=app_dot_proto_dot_session__manager__pb2.SessionCreatedRequest.SerializeToString,
                response_deserializer=app_dot_proto_dot_session__manager__pb2.SessionResponse.FromString,
                )
        self.OnSessionUpdated = channel.unary_unary(
                '/accelbyte.session.manager.SessionManager/OnSessionUpdated',
                request_serializer=app_dot_proto_dot_session__manager__pb2.SessionUpdatedRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.OnSessionDeleted = channel.unary_unary(
                '/accelbyte.session.manager.SessionManager/OnSessionDeleted',
                request_serializer=app_dot_proto_dot_session__manager__pb2.SessionDeletedRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.OnPartyCreated = channel.unary_unary(
                '/accelbyte.session.manager.SessionManager/OnPartyCreated',
                request_serializer=app_dot_proto_dot_session__manager__pb2.PartyCreatedRequest.SerializeToString,
                response_deserializer=app_dot_proto_dot_session__manager__pb2.PartyResponse.FromString,
                )
        self.OnPartyUpdated = channel.unary_unary(
                '/accelbyte.session.manager.SessionManager/OnPartyUpdated',
                request_serializer=app_dot_proto_dot_session__manager__pb2.PartyUpdatedRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.OnPartyDeleted = channel.unary_unary(
                '/accelbyte.session.manager.SessionManager/OnPartyDeleted',
                request_serializer=app_dot_proto_dot_session__manager__pb2.PartyDeletedRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class SessionManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OnSessionCreated(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnSessionUpdated(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnSessionDeleted(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnPartyCreated(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnPartyUpdated(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnPartyDeleted(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnSessionCreated': grpc.unary_unary_rpc_method_handler(
                    servicer.OnSessionCreated,
                    request_deserializer=app_dot_proto_dot_session__manager__pb2.SessionCreatedRequest.FromString,
                    response_serializer=app_dot_proto_dot_session__manager__pb2.SessionResponse.SerializeToString,
            ),
            'OnSessionUpdated': grpc.unary_unary_rpc_method_handler(
                    servicer.OnSessionUpdated,
                    request_deserializer=app_dot_proto_dot_session__manager__pb2.SessionUpdatedRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'OnSessionDeleted': grpc.unary_unary_rpc_method_handler(
                    servicer.OnSessionDeleted,
                    request_deserializer=app_dot_proto_dot_session__manager__pb2.SessionDeletedRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'OnPartyCreated': grpc.unary_unary_rpc_method_handler(
                    servicer.OnPartyCreated,
                    request_deserializer=app_dot_proto_dot_session__manager__pb2.PartyCreatedRequest.FromString,
                    response_serializer=app_dot_proto_dot_session__manager__pb2.PartyResponse.SerializeToString,
            ),
            'OnPartyUpdated': grpc.unary_unary_rpc_method_handler(
                    servicer.OnPartyUpdated,
                    request_deserializer=app_dot_proto_dot_session__manager__pb2.PartyUpdatedRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'OnPartyDeleted': grpc.unary_unary_rpc_method_handler(
                    servicer.OnPartyDeleted,
                    request_deserializer=app_dot_proto_dot_session__manager__pb2.PartyDeletedRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'accelbyte.session.manager.SessionManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SessionManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OnSessionCreated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/accelbyte.session.manager.SessionManager/OnSessionCreated',
            app_dot_proto_dot_session__manager__pb2.SessionCreatedRequest.SerializeToString,
            app_dot_proto_dot_session__manager__pb2.SessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OnSessionUpdated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/accelbyte.session.manager.SessionManager/OnSessionUpdated',
            app_dot_proto_dot_session__manager__pb2.SessionUpdatedRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OnSessionDeleted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/accelbyte.session.manager.SessionManager/OnSessionDeleted',
            app_dot_proto_dot_session__manager__pb2.SessionDeletedRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OnPartyCreated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/accelbyte.session.manager.SessionManager/OnPartyCreated',
            app_dot_proto_dot_session__manager__pb2.PartyCreatedRequest.SerializeToString,
            app_dot_proto_dot_session__manager__pb2.PartyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OnPartyUpdated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/accelbyte.session.manager.SessionManager/OnPartyUpdated',
            app_dot_proto_dot_session__manager__pb2.PartyUpdatedRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OnPartyDeleted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/accelbyte.session.manager.SessionManager/OnPartyDeleted',
            app_dot_proto_dot_session__manager__pb2.PartyDeletedRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
